version: "3"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=simple_bank
    ports:
      - "5000:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - CUSTOMERS_HOST=postgres
    ports:
      - 8080:8080
